models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $auth_key
 * @property string $email
 * @property string $address
 * @property int $type
 * @property int $agreement
 * @property int $status
 * @property string $updated_at
 * @property string $password
 * @property string $authKey
 * @property string $created_at
 * @property string $verification_token
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    public $password;
    /**
     *
     */
    const STATUS_DELETED = 0;
    /**
     *
     */
    const STATUS_INACTIVE = 9;
    /**
     *
     */
    const STATUS_ACTIVE = 10;

    const TYPE_ADMIN = 1;
    const TYPE_USER = 0;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'status'], 'default', 'value' => null],
            [['type', 'status', 'agreement'], 'integer'],
            [['updated_at', 'created_at'], 'required'],
            [['updated_at', 'created_at', 'password'], 'safe'],
            [['username', 'password_hash', 'password_reset_token', 'auth_key', 'email', 'address', 'verification_token'], 'string', 'max' => 255],
            [['username'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
            'password_hash' => Yii::t('app', 'Password Hash'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'email' => Yii::t('app', 'Email'),
            'address' => Yii::t('app', 'Address'),
            'type' => Yii::t('app', 'Type'),
            'status' => Yii::t('app', 'Status'),
            'updated_at' => Yii::t('app', 'Update At'),
            'created_at' => Yii::t('app', 'Create At'),
        ];
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }
    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }


    /**
     * @param $username
     * @return User|null
     */
    public static function findByAdmin($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE, 'type' => self::TYPE_ADMIN]);
    }
    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }
        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }
    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token) {
        return static::findOne([
            'verification_token' => $token,
            'status' => self::STATUS_INACTIVE
        ]);
    }
    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }
    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }
    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }
    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }
    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }
    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }
    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }
    /**
     * Generates new token for email verification
     */
    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }
    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getUserStatus(){
        if($this->status == 10) {
            return 'Активный';
        } else {
            return 'Отключен';
        }
    }

    public function getCommentCount(){
        return CollectionForum::find()->where(['user_id' => $this->id])->count();
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Authorization\ResendVerificationEmailForm;
use app\models\Authorization\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Authorization\LoginForm;
use app\models\Authorization\PasswordResetRequestForm;
use app\models\Authorization\ResetPasswordForm;
use app\models\Authorization\SignupForm;
use app\models\Authorization\ContactForm;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = 'type';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/type/index');
        } else {
            $model->password = '';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }
            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout = 'type';
        $model = new SignupForm();
        $user = null;
        if ($model->load(Yii::$app->request->post()) && $user = $model->signup()['user']) {
            Yii::$app->user->login($user, true ? 3600 * 24 * 30 : 0);
            Yii::$app->session->setFlash('register', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->redirect('profile');
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }
        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');
            return $this->goHome();
        }
        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @return yii\web\Response
     * @throws BadRequestHttpException
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }
        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }
        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionProfile(){
        $this->layout = 'type';
        if(!Yii::$app->user->isGuest){
            return $this->render('profile');
        } else {
            return $this->redirect('login');
        }
    }
}

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php

use yii\widgets\ActiveForm;

?>
<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Главная</a></li>
                <li class="breadcrumb-item active">Личный кабинет</li>
            </ol>
        </nav>
    </div>
</section>
<!-- section-title-->
<div class="section-title">
    <div class="container">
        <h1>Авторизация</h1>
    </div>
</div>
<!-- login-->
<section class="form-section">
    <div class="container">
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <div class="login-form row">
                <div class="ui-group login-field">
                    <?php echo $form->field($model, 'username', [
                        'template' => '{input}{error}',
                        'options' => [
                            'tag' => false,
                        ]])->textInput([
                        'maxlength' => true,
                        'placeholder' => 'Введите ваш логин'
                    ])->label(false) ?>

                </div>
                <div class="ui-group login-field">
                    <?php echo $form->field($model, 'password', [
                        'template' => '{input}{error}',
                        'options' => [
                            'tag' => false,
                        ]])->textInput([
                        'maxlength' => true,
                        'placeholder' => 'Введите пароль',
                        'type' => 'password'
                    ])->label(false) ?>

                </div>
                <div class="ui-group login-send">
                    <button class="btn"><span class="arrow-txt">Войти</span><span class="arrow-icon">
                      <svg class="ico ico-arrow-angle">
                        <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                      </svg></span></button>
                </div>
                <div class="login-form-info row">
                    <div class="ui-checkbox">
                        <label for="remember">Запомнить меня</label>
                        <input id="remember" type="checkbox" name="">
                    </div>
                    <div class="login-link row"><a href="#">Я уже зарегестрирован</a><a href="#">Забыли пароль?</a>
                    </div>
                </div>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</section>

views/site/profile.php
<?php

use yii\helpers\Url;

$user = Yii::$app->user->identity;

?>
<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?=Url::to(['type/index'])?>">Главная</a></li>
                <li class="breadcrumb-item active"> Личный кабинет</li>
            </ol>
        </nav>
    </div>
</section>
<!-- lk-section-->
<section class="lk-section decor-lines">
    <div class="container">
        <!-- section-title-->
        <div class="section-title">
            <h1>Личный кабинет</h1>
        </div>
        <div class="lk row">
            <!-- img-->
            <div class="lk__img linear-gradient-right"><img src="/typewriter/img/lk/lk-img.png" alt=""></div>
            <!-- info-->
            <div class="lk__info">
                <!-- settings-->
                <button class="settings-btn">
                    <svg class="ico ico-settings">
                        <use xlink:href="/typewriter/img/sprite.svg#ico-settings"></use>
                    </svg>
                </button>
                <!-- line-->
                <div class="lk-info-line row">
                    <!-- i-->
                    <div class="lk-info-line__item row"><span>Имя:</span>
                        <p><?=$user->username?></p>
                    </div>
                    <!-- i-->
<!--                    <div class="lk-info-line__item row"><span>Номер телефона:</span><a href="tel:--><?//=$user->phone?><!--">--><?//=$user->phone?><!--</a></div>-->
                    <!-- i-->
                    <div class="lk-info-line__item row"><span>E-mail:</span><a href="mailto:<?=$user->email?>"><?=$user->email?></a></div>
                    <!-- i-->
                    <div class="lk-info-line__item row"><span>Адрес:</span>
                        <p><?=$user->address?></p>
                    </div>
                </div>
                <!-- line-->
                <div class="lk-info-line row">
                    <!-- i-->
                    <div class="lk-info-line__item row"><span>Дата регистрации:</span>
                        <p><?=Yii::$app->formatter->asDate($user->created_at, 'dd.mm.yyyy')?></p>
                    </div>
                    <!-- i-->
                    <div class="lk-info-line__item row"><span>Дата изменений:</span>
                        <p><?=Yii::$app->formatter->asDate($user->updated_at, 'dd.mm.yyyy')?></p>
                    </div>
                    <!-- i-->
                    <div class="lk-info-line__item row"><span>Комментарии на форуме:</span>
                        <p><?=$user->commentCount?></p>
                    </div>
                    <!-- i-->
                    <div class="lk-info-line__item row"><span>Статус:</span>
                        <p><?=$user->userStatus?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="lk-btn">
            <button class="btn-transparent hover-link js-popup" data-mfp-src="#modal-form-logout"><span class="arrow-txt">Выйти</span><span class="arrow-icon">
                  <svg class="ico ico-arrow-angle">
                    <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                  </svg></span></button>
        </div>
        <div class="modal-content mfp-hide white-popup-block my-mfp-slide-bottom modal-logout" id="modal-form-logout">
            <div class="popup-buble">
                <div class="popup-dialog row">
                    <div class="logout-wrapper row">
                        <h3>Вы уверены, что хотите выйти?</h3>
                        <div class="logout-btn row">
                            <a class="btn logout-btn__item" href="<?=Url::to(['site/logout'])?>">Да</a>
                            <a class="btn-transparent logout-btn__item " id="profile_modal_close_button">Нет</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php

$this->registerJs("

$('body').on('click', '#profile_modal_close_button', function(){

    console.log('closed');
    
    $('.mfp-close').trigger('click');

})

")

?>

views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A verification email will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/signup.php
<?php

use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>
<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Главная</a></li>
                <li class="breadcrumb-item active">Личный кабинет</li>
            </ol>
        </nav>
    </div>
</section>
<!-- section-title-->
<div class="section-title">
    <div class="container">
        <h1>Регистрация</h1>
    </div>
</div>
<!-- login-->
<section class="form-section">
    <div class="container">
        <?php
        $form = ActiveForm::begin(['id' => 'form-signup']); ?>
        <!-- registration-->
        <div class="registration-wrapper row">
            <!-- ui-->
            <div class="ui-group">
                <?php echo $form->field($model, 'username', [
                    'template' => '{input}{error}',
                   ])->textInput([
                    'maxlength' => true,
                    'placeholder' => 'Ваше имя'
                ])->label(false) ?>

            </div>


            <!-- ui-->
            <div class="ui-group">
                <?php echo $form->field($model, 'email', [
                    'template' => '{input}{error}',
                    ])->textInput([
                    'maxlength' => true,
                    'placeholder' => 'Ваш e-mail'
                ])->label(false) ?>
            </div>
            <!-- ui-->
            <div class="ui-group">
                <?php echo $form->field($model, 'password', [
                    'template' => '{input}{error}',
                   ])->passwordInput([
                    'maxlength' => true,
                    'placeholder' => 'Введите пароль',
                ])->label(false) ?>
            </div>
            <!-- ui-->
            <div class="ui-group submit-btn">
                <button class="btn" type="submit"><span class="arrow-txt">Зарегестрироваться</span><span
                            class="arrow-icon">
                      <svg class="ico ico-arrow-angle">
                        <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                      </svg></span></button>
            </div>
            <!-- ui-->
            <div class="ui-checkbox">
                <label for="remember">Согласие на обработку <a href="<?=Url::to(['type/personal-agreement'])?>">персональных данных</a></label>

                        <?= $form->field($model, 'agreement', [
                            'template' => '{input}{error}',
                            ])->checkbox([
                            'label' => false,
                            'id' => 'remember',
                            'hidden' => false,
                            //'class' => ''
                        ])->label(false)?>

            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</section>