controllers/TypeController.php
<?php

namespace app\controllers;

use app\models\BrandSlider;
use app\models\Collection;
use app\models\CollectionEvents;
use app\models\CollectionForum;
use app\models\CollectionModelCharacteristics;
use app\models\CollectionModels;
use app\models\Comments;
use app\models\ForumThemes;
use app\models\News;
use app\models\PageTypes;
use app\models\Partners;
use app\models\PersonalAgreement;
use app\models\PoliticalConfidency;
use app\models\StandardPages;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

/**
 * Class TypeController
 * @package app\controllers
 */
class TypeController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $brandSlider = BrandSlider::find()->all();
        $collectionModels = CollectionModels::find()->all();
        $news = News::find()->limit(6)->all();
        $partners = Partners::find()->limit(3)->all();
        return $this->render('index', [
            'brandSlider' => $brandSlider,
            'collectionModels' => $collectionModels,
            'news' => $news,
            'partners' => $partners
        ]);
    }

    /**
     * @return string
     */
    public function actionCatalog()
    {
        return $this->render('catalog');
    }

    /**
     * @return string
     */
    public function actionCatalogPartial()
    {
        $search = Yii::$app->request->get('search');
        $limit = Yii::$app->request->get('limit');
        $catalogs = Collection::find();

        if ($search) {
            $limit = null;
            $catalogs = $catalogs->where(['like', 'LOWER(name)', $search]);
        }

        if ($limit != null && $limit != 0) {
            $catalogs = $catalogs->limit($limit)->all();
        } else {
            $catalogs = $catalogs->all();
        }

        $content = $this->renderPartial('catalog_partial', [
            'catalogs' => $catalogs,
        ]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $content;
    }

    /**
     * @param $slug
     * @return string
     */
    public function actionOneCollection($slug)
    {
        $collection = Collection::find()->where(['slug' => $slug])->one();
        return $this->render('one-catalog', [
            'collection' => $collection
        ]);
    }

    /**
     * @param $slug
     * @return string
     */
    public function actionCollectionModels($slug)
    {
        $collection = Collection::find()->where(['slug' => $slug])->one();
        return $this->render('collection_models', [
            'collection' => $collection,
        ]);
    }

    /**
     * @return string
     */
    public function actionCollectionModelsPartial()
    {
        $symbol = Yii::$app->request->get('symbol');
        $search = Yii::$app->request->get('search');
        $limit = Yii::$app->request->get('limit');
        $collectionId = Yii::$app->request->get('collection_id');
        $models = CollectionModels::find()->where(['collection_id' => $collectionId]);
        $collection = Collection::findOne(['id' => $collectionId]);

        if ($symbol) {
            $models = $models->andWhere(['start_symbol' => $symbol]);
            $limit = null;
        }

        if ($search) {
            $limit = null;
            $models = $models->andWhere(['like', 'name', $search]);
        }

        if ($limit != null && $limit != 0) {
            $models = $models->limit($limit)->all();
        } else {
            $models = $models->all();
        }

        $content = $this->renderPartial('collection_models_partial', [
            'models' => $models,
        ]);

        $result = [
            'collection' => $collection,
            'content' => $content,
        ];

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $result;
    }

    /**
     * @param $slug
     * @return string
     */
    public function actionCollectionForum($slug = null)
    {
        $collection = Collection::findOne(['slug' => $slug]);
        $forumTheme = ForumThemes::find()->where(['collection_id' => $collection->id])->limit(1)->one();
        $forumComments = CollectionForum::find()
            ->where(['forum_theme_id' => $forumTheme->id])
            ->orderBy(['id' => SORT_DESC]);
        $new_comment = new CollectionForum();

        if ($new_comment->load(Yii::$app->request->post())) {
            $new_comment->save(false);
            $this->redirect(Yii::$app->request->referrer);
        }

        $provider = new ActiveDataProvider([
            'query' => $forumComments,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        $comments = $provider->getModels();

        return $this->render('collection_forum', [
            'forumTheme' => $forumTheme,
            'forumComments' => $comments,
            'new_comment' => $new_comment,
            'childValue' => null,
            'provider' => $provider,
        ]);
    }


    /**
     * @return array
     */
    public function actionForumPartial()
    {

        $theme_id = Yii::$app->request->get('theme_id');
        $offset = Yii::$app->request->get('offset');
        $forumComments = CollectionForum::find()
            ->where(['forum_theme_id' => $theme_id])
            ->orderBy(['id' => SORT_DESC])
            ->where(['parent_id' => null])
            ->limit(2)->offset($offset)
            ->all();
        $new_comment = new CollectionForum();

        $content = $this->renderPartial('forum_partial', [
            'theme_id' => $theme_id,
            'forumComments' => $forumComments,
            'new_comment' => $new_comment,
        ]);

        $result = [
            'content' => $content,
            'offset' => $offset + 2,
        ];

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $result;
    }

    /**
     * @param $slug
     * @return string
     */
    public function actionOneModel($slug)
    {
        $model = CollectionModels::find()->where(['slug' => $slug])->one();
        return $this->render('one_model', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionNews()
    {
        return $this->render('news');
    }

    /**
     * @return string
     */
    public function actionNewsPartial()
    {

        $all = Yii::$app->request->get('all');
        if ($all) {
            $news = News::find()->orderBy(['id' => SORT_DESC])->all();
        } else {
            $news = News::find()->orderBy(['id' => SORT_DESC])->limit(10)->all();
        }
        $content = $this->renderPartial('news_partial', [
            'news' => $news,
        ]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $content;
    }

    /**
     * @param $slug
     * @return string
     */
    public function actionOneNews($slug)
    {
        $model = News::findOne(['slug' => $slug]);
        $news = News::find()->all();
        return $this->render('one_news', [
            'model' => $model,
            'news' => $news,
        ]);
    }


    public function actionCommentSave()
    {
        $comment = new Comments();
        if ($comment->load(Yii::$app->request->post()) && $comment->validate()) {
            if ($comment->save()) {
                Yii::$app->session->setFlash('success', "Your message has been sent successfully!");
            }
        }
        $this->redirect(Yii::$app->request->referrer);
    }

    public function actionPoliticalConfident()
    {
        $model = PoliticalConfidency::find()->limit(1)->one();
        return $this->render('political-confident', [
            'model' => $model,
        ]);
    }

    public function actionPersonalAgreement()
    {
        $model = PersonalAgreement::find()->limit(1)->one();
        return $this->render('personal-agreement', [
            'model' => $model,
        ]);
    }


    public function actionStandardPages($page_id)
    {
        $pageType = PageTypes::findOne(['id' => $page_id]);
        $page = StandardPages::find()->where(['page_type_id' => $page_id])->orderBy(['id' => SORT_DESC]);

        if ($pageType->page_type == PageTypes::MULTIPAGE) {
            $pages = $page->all();
            Yii::$app->controller->action->id = 'multipage';
            return $this->render('multi_pages', [
                'pages' => $pages,
                'pageType' => $pageType
            ]);
        } else if ($pageType->page_type == PageTypes::SINGLE_PAGE) {
            $page = $page->one();
            Yii::$app->controller->action->id = 'single_page';
            return $this->render('single_pages', [
                'page' => $page,
                'pageType' => $pageType
            ]);
        }

        return null;
    }

    public function actionSinglePage($slug)
    {

views/type/multi_pages.php
<?php

use yii\helpers\Url;

?>
<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?=Url::to(['type/index'])?>">Главная</a></li>
                <li class="breadcrumb-item active"><?=$pageType->name?></li>
            </ol>
        </nav>
    </div>
</section>
<!-- all-news-->
<main class="all-news-section">
    <div class="container">
        <!-- title-->
        <div class="section-title">
            <h1><?=$pageType->name?></h1>
        </div>
        <!-- all-news-->
        <div class="company-news-content row">
            <div class="company-news-content-col row">
                <?php

                foreach($pages as $pagesKey=> $pagesItem):?>
                    <?php if($pagesKey >= 3) { break;}?>
                    <?php $class = 'full-item'; if($pagesKey > 0) { $class = 'half-item';}?>
                    <div class="company-news-content__item row <?=$class?>">
                        <!-- img -->
                        <div class="company-news-img"><img src="/uploads<?=$pagesItem->image?>" alt=""/></div>
                        <!-- txt-->
                        <div class="company-news-txt">
                            <h3><?=$pagesItem->title?></h3>
                            <?php if($pagesKey == 0):?>
                                <p><?=mb_substr(strip_tags(htmlspecialchars_decode($pagesItem->text)), 0, 287)?></p>
                            <?php endif;?>
                            <?php if($pagesKey == 1 || $pagesKey == 2):?>
                                <p><?=mb_substr(strip_tags(htmlspecialchars_decode($pagesItem->text)), 0, 287)?></p>
                            <?php endif;?>
                            <!-- info-->
                            <div class="company-news-info row">
                                <div class="news-link">
                                    <a class="hover-link" href="<?=Url::to(['/type/single-page', 'slug' => $pagesItem->slug])?>">
                                        <span class="arrow-txt"><?=Yii::t('type','Подробнее')?></span><span class="arrow-icon">
                            <svg class="ico ico-arrow-angle">
                              <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                            </svg>
                        </span>
                                    </a>
                                </div>
                                <div class="news-date">
                                    <date><?=Yii::$app->formatter->asDate($pagesItem->created_at)?></date>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach;?>

            </div>
            <div class="company-news-content-col news-negative-margin row">
                <?php foreach($pages as $pagesKey=> $pagesItem):?>
                    <?php if($pagesKey <= 2) { continue;}?>
                    <?php $class = 'one-third-item'; if($pagesKey == 6) { $class = 'full-item';}?>
                    <div class="company-news-content__item row <?=$class?>">
                        <!-- img -->
                        <?php if($pagesKey == 6):?>
                            <div class="company-news-img"><img src="/uploads<?=$pagesItem->image?>" alt=""/></div>
                        <?php endif;?>
                        <?php if($pagesKey != 6):?>
                            <div class="company-news-img"><img src="" alt=""/></div>
                        <?php endif;?>
                        <!-- txt-->
                        <div class="company-news-txt">
                            <h3><?=$pagesItem->title?></h3>
                            <?php if($pagesKey >=3):?>
                                <p><?=mb_substr(strip_tags(htmlspecialchars_decode($pagesItem->text)), 0, 130)?></p>
                            <?php endif;?>
                            <!-- info-->
                            <div class="company-news-info row">
                                <div class="news-link">
                                    <a class="hover-link" href="<?=Url::to(['/type/one-news', 'slug' => $pagesItem->slug])?>"><span class="arrow-txt"><?=Yii::t('type','Подробнее')?></span><span class="arrow-icon">
                            <svg class="ico ico-arrow-angle">
                              <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                            </svg></span></a></div>
                                <div class="news-date">
                                    <date><?=Yii::$app->formatter->asDate($pagesItem->created_at, 'dd.mm.yyyy')?></date>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>

    </div>
</main>

views/type/one-catalog.php
<?php

use yii\helpers\Url;

?>

<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= Url::to(['/type/index']) ?>"><?=Yii::t('type','Главная')?></a></li>
                <li class="breadcrumb-item"><a href="<?= Url::to(['/type/catalog']) ?>"><?=Yii::t('type','Коллекции')?></a></li>
                <li class="breadcrumb-item active"><?= $collection ? $collection->title : 'Нет такого' ?></li>
            </ol>
        </nav>
    </div>
</section>
<!-- .card-collection-info-->
<main class="card-collection-info decor-lines">
    <div class="container">
        <!-- top-info-->
        <div class="card-collection-top-info row">
            <div class="section-title">
                <h1><?= $collection->title ?></h1>
            </div>
            <div class="card-logo"><img src="/uploads<?= $collection->logo ?>" alt=""></div>
        </div>
        <!-- collection-carousel-->
        <div class="card-collection-carousel">
            <div class="swiper-container swiper-collection-carousel">
                <div class="swiper-wrapper">
                    <?php if ($collection->collectionImages): ?>
                        <?php foreach ($collection->collectionImages as $image): ?>
                            <div class="swiper-slide row"><img src="/uploads<?= $image->image ?>" alt=""></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <!-- card-model-info-wrapper-->
        <div class="card-model-info-wrapper row">
            <!-- item-->
            <div class="card-model-info-wrapper__item collection-txt">
                <h2><?=Yii::t('type','История')?></h2>
                <div class="card-model-description-wrapper">
                    <article class="card-model-description">
                        <?= $collection->history ?>
                    </article>
                </div>
                <div class="card-model-btns row">
                    <a class="btn" href="<?=Url::to(['type/collection-models', 'slug' => $collection->slug])?>">
                        <span class="arrow-txt"><?=Yii::t('type','Модели')?></span>
                        <span class="arrow-icon">
                      <svg class="ico ico-arrow-angle">
                        <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                      </svg></span></a>
                    <a class="hover-link btn-transparent" href="<?=Url::to(['type/collection-forum', 'slug' => $collection->slug])?>">
                        <span class="arrow-txt"><?=Yii::t('type','Форум')?></span>
                        <span class="arrow-icon"><svg class="ico ico-arrow-angle">
                        <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                        </svg>
                        </span>
                    </a>
                </div>
            </div>
            <!-- item-->
            <div class="card-model-info-wrapper__item collection-carousel">
                <h2>События</h2>
                <div class="swiper-container events-swiper-container">
                    <div class="swiper-wrapper">
                        <?php if ($collection->collectionEvents): ?>
                            <?php foreach ($collection->collectionEvents as $event): ?>
                                <div class="swiper-slide collection-carousel-item">
                                    <time><?= $event->event_date ?></time>
                                    <p><?= $event->event_description ?></p>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="nav-btn row">
                        <div class="nav-btn-next nav-border swiper-button-prev events-button-prev">
                            <svg class="ico ico-arrow-angle">
                                <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                            </svg>
                        </div>
                        <div class="nav-btn-prev nav-border swiper-button-next events-button-next">
                            <svg class="ico ico-arrow-angle">
                                <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- additional-materials-->
<section class="additional-materials-section">
    <div class="container">
        <div class="section-title">
            <h3><?=Yii::t('type','Дополнительные материалы')?></h3>
        </div>
        <!-- additional-materials-->
        <div class="additional-materials row">
            <!-- carousel-->
            <div class="additional-materials-carousel additional-materials__item">
                <!-- materials-top-->
                <?php if ($collection->collectionDetails): ?>
                <div class="materials-top swiper-container">
                    <div class="swiper-wrapper">

                            <?php foreach ($collection->collectionDetails as $detail): ?>
                                <div class="swiper-slide row"><img src="/uploads<?= $detail->image ?>" alt=""></div>
                            <?php endforeach; ?>

                    </div>
                    <div class="materials-button-next swiper-button-next nav-btn-next gallery-next">
                        <svg class="ico ico-arrow-angle">
                            <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                        </svg>
                    </div>
                    <div class="materials-button-prev swiper-button-prev nav-btn-prev gallery-prev">
                        <svg class="ico ico-arrow-angle">
                            <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                        </svg>
                    </div>
                </div>
                <?php endif ?>
                <!-- materials-thumbs-->
                <?php if ($collection->collectionDetails): ?>
                <div class="materials-thumbs swiper-container">
                    <div class="swiper-wrapper">


                            <?php foreach ($collection->collectionDetails as $detail): ?>
                                <div class="swiper-slide row"><img src="/uploads<?= $detail->image ?>" alt=""></div>
                            <?php endforeach; ?>

                    </div>
                </div>
                <?php endif ?>
            </div>
            <!-- download-->
            <?php if ($collection->collectionFiles): ?>
            <div class="additional-materials-download additional-materials__item">
                <div class="swiper-container swiper-container-download">
                    <div class="swiper-wrapper">

                            <?php foreach ($collection->collectionFiles as $document): ?>
                                <div class="swiper-slide">
                                    <div class="additional-materials-download__item">
                                        <!-- title-->
                                        <div class="materials-download-info row">
                                            <div class="materials-download-info__icon">
                                                <svg class="ico ico-download">
                                                    <use xlink:href="/typewriter/img/sprite.svg#ico-download"></use>
                                                </svg>
                                            </div>
                                            <div class="materials-download-info__title">
                                                <p><?= $document->name ?></p>
                                                <!-- btn-->
                                                <div class="materials-download-btn"><a class="hover-link"
                                                                                       href="/uploads<?= $document->file ?>"
                                                                                       download=>
                                                        <span class="arrow-txt"><?=Yii::t('type','Скачать')?></span>
                                                        <span class="arrow-icon">
                                                            <svg class="ico ico-arrow-angle">
                                                                <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                                                            </svg>
                                                        </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>

                    </div>
                </div>
                <div class="download-btns row">
                    <div class="download-button-prev nav-border download-btn nav-btn-next">
                        <svg class="ico ico-arrow-angle">
                            <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                        </svg>
                    </div>
                    <div class="download-button-next nav-border download-btn nav-btn-prev">
                        <svg class="ico ico-arrow-angle">
                            <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                        </svg>
                    </div>
                </div>
            </div>
            <?php endif ?>
        </div>
    </div>
</section>

views/type/one_news.php
<?php

use yii\helpers\Url;

?>
<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?=Url::to(['/type/index'])?>"><?=Yii::t('type','Главная')?></a></li>
                <li class="breadcrumb-item"><a href="<?=Url::to(['/type/news'])?>"><?=Yii::t('type','Новости')?></a></li>
                <li class="breadcrumb-item active"><?=$model->title?></li>
            </ol>
        </nav>
    </div>
</section>
<article class="news-article">
    <div class="container">
        <div class="news-article-img"> <img src="/uploads<?=$model->image?>" alt=""></div>
        <div class="section-title">
            <h1><?=Yii::t('type','Страница новости')?></h1>
        </div>
        <div class="news-article-wrapper">
            <h2><?=$model->title?></h2>
           <?=htmlspecialchars_decode($model->text)?>
            <div class="article-date row">
                <p><?=Yii::t('type','Добавлено')?> : <?=$model->posted_date?></p>
            </div>
        </div>
    </div>
</article>
<section class="news-more">
    <div class="container">
        <div class="section-title">
            <h2><?=Yii::t('type','Читайте также')?></h2>
        </div>
        <div class="swiper-container news-more-container">
            <div class="swiper-wrapper">
                <?php foreach($news as $newsKey=>$newsItem):?>
                <div class="swiper-slide">
                    <div class="company-news-content__item row news-slide-more">
                        <!-- img -->
                        <div class="company-news-img"><img src="/uploads<?=$newsItem->image?>" alt=""/></div>
                        <!-- txt-->
                        <div class="company-news-txt">
                            <h3><?=$newsItem->title?></h3>
                            <!-- info-->
                            <div class="company-news-info row">
                                <div class="news-link"><a class="hover-link" href="<?=Url::to(['/type/one-news', 'slug' => $newsItem->slug])?>"><span class="arrow-txt"><?=Yii::t('type','Подробнее')?></span><span class="arrow-icon">
                              <svg class="ico ico-arrow-angle">
                                <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
                              </svg></span></a></div>
                                <div class="news-date">
                                    <date><?=$newsItem->posted_date?></date>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach;?>
            </div>
        </div>
        <div class="swiper-button-prev news-button-prev nav-btn-next nav-border">
            <svg class="ico ico-arrow-angle">
                <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
            </svg>
        </div>
        <div class="swiper-button-next news-button-next nav-btn-prev nav-border">
            <svg class="ico ico-arrow-angle">
                <use xlink:href="/typewriter/img/sprite.svg#ico-arrow-angle"></use>
            </svg>
        </div>
    </div>
</section>

views/type/personal-agreement.php
<?php

use yii\helpers\Url;

?>
<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?=Url::to(['/type/index'])?>"><?=Yii::t('type','Главная')?></a></li>
                <li class="breadcrumb-item"><a href="<?=Url::to(['/type/news'])?>"><?=Yii::t('type','Новости')?></a></li>
                <li class="breadcrumb-item active"><?=$model->title?></li>
            </ol>
        </nav>
    </div>
</section>
<article class="news-article">
    <div class="container">
        <div class="news-article-img"> <img src="/uploads<?=$model->image?>" alt=""></div>
        <div class="section-title">
            <h1><?=Yii::t('type','Cогласие на обработку пресональных данных')?></h1>
        </div>
        <div class="news-article-wrapper">
            <h2><?=$model->title?></h2>
            <?=htmlspecialchars_decode($model->text)?>
            <div class="article-date row">
                <p><?=Yii::t('type','Добавлено')?> : <?=Yii::$app->formatter->asDate($model->created_at, 'dd.mm.yyyy')?></p>
            </div>
        </div>
    </div>
</article>

views/type/political-confident.php
<?php

use yii\helpers\Url;

?>
<section class="breadcrumbs">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?=Url::to(['/type/index'])?>"><?=Yii::t('type','Главная')?></a></li>
                <li class="breadcrumb-item"><a href="<?=Url::to(['/type/news'])?>"><?=Yii::t('type','Новости')?></a></li>
                <li class="breadcrumb-item active"><?=$model->title?></li>
            </ol>
        </nav>
    </div>
</section>
<article class="news-article">
    <div class="container">
        <div class="news-article-img"> <img src="/uploads<?=$model->image?>" alt=""></div>
        <div class="section-title">
            <h1><?=Yii::t('type','Политика конфидециальности')?></h1>
        </div>
        <div class="news-article-wrapper">
            <h2><?=$model->title?></h2>
            <?=htmlspecialchars_decode($model->text)?>
            <div class="article-date row">
                <p><?=Yii::t('type','Добавлено')?> : <?=Yii::$app->formatter->asDate($model->created_at, 'dd.mm.yyyy')?></p>
            </div>
        </div>
    </div>
</article>